### ISSUE TITLE
Tags not added by on-add hook

### ISSUE THREAD

**Issue by akanekurosawa** [guludo/taskwarrior-autotagger#1]
Environment Info:
TaskWarrior 3.0.2
Python 3.12.1
macOS 14.4.1

When adding a new task that meets the criteria set in autotagger.cfg, output claims that it added the associated tag, but no tag is actually added.

My autotagger.cfg
```
[tag.Mods]
projects = Stardew

[tag.MMO]
tags = OSRS
```

When I run `task add +OSRS Zulrah` or `task add Skins project:Stardew`, I get output to the effect of "autotagger: added the following tags: Mods" or "[...] tags: MMO" as expected, however the tag isn't actually added to the task.

However, using `task 1 modify project:Stardew` successfully adds the tag Mods as expected.

I dug around in the hook code for a while, and even tried creating a separate on-add hook (in case there was an issue with the add/modify conditional), but haven't been able to figure out what's going wrong. 

I'll note that I don't have much experience with python, so I apologize if this is something obvious that I'm just not noticing.

Thanks in advance!

**Comment by guludo** [comment]
Hey, @akanekurosawa.

Thanks for raising this issue. I just tested and this is happening to me as well.

I believe this is happening due to a regression in taskwarrior. This seems to be the related issue: https://github.com/GothenburgBitFactory/taskwarrior/issues/3416

**Comment by akanekurosawa** [comment]
This issue has been resolved in taskwarrior 3.1.0 by [#3443](https://github.com/GothenburgBitFactory/taskwarrior/pull/3443)
